"""Generate the independently deployable Flutter copy of the voice catalog.

python -m app_voice_assistant.generate_catalog --check --output ../DatingApp/lib/services/app_voice/app_voice_capabilities.dart
"""
import argparse
import json
from pathlib import Path


def generate():
    catalog = json.loads(Path(__file__).with_name('capabilities.json').read_text())
    def dart(value):
        # JSON string syntax is valid Dart here except that `$` starts string
        # interpolation in Dart. Preserve schema regex anchors as literal data.
        return json.dumps(value, ensure_ascii=False).replace('$', r'\$')
    rows = []
    for name, action in catalog['actions'].items():
        rows.append(f'  {dart(name)}: {dart(action["permission"])},')
    kinds = [f'  {dart(name)}: <String>{dart(action["target_kinds"])},'
             for name, action in catalog['actions'].items() if action['target_kinds']]
    parameters = [f'  {dart(name)}: <String>{dart(action["parameters"])},'
                  for name, action in catalog['actions'].items() if action['parameters']]
    target_permissions = [f'  {dart(name)}: <String>{dart(action["target_permissions"])},'
                          for name, action in catalog['actions'].items() if 'target_permissions' in action]
    titles = [f'  {dart(name)}: {dart(action["title"])},'
              for name, action in catalog['actions'].items()]
    execution_kinds = [f'  {dart(name)}: {dart(action["execution_kind"])},'
                       for name, action in catalog['actions'].items()]
    risks = [f'  {dart(name)}: {dart(action["risk"])},'
             for name, action in catalog['actions'].items()]
    cancellable = [f'  {dart(name)}: {str(action["cancellable"]).lower()},'
                   for name, action in catalog['actions'].items()]
    argument_schemas = [f'  {dart(name)}: {dart(schema)},'
                        for name, schema in catalog['argument_schemas'].items()]
    routine_templates = catalog['actions'].get('routine.save', {}).get(
        'routine_templates', {}
    )
    search_domains = (
        catalog['argument_schemas'].get('app.search', {})
        .get('properties', {}).get('domains', {})
        .get('items', {}).get('enum', [])
    )
    return ('// Generated by Server/app_voice_assistant/generate_catalog.py. Do not edit.\n'
            f'const appVoiceCatalogVersion = {catalog["version"]};\n'
            'const appVoiceRoutineTemplates = <String, Map<String, dynamic>>' + dart(routine_templates) + ';\n'
            'const appVoiceSearchDomains = <String>' + dart(search_domains).replace('[', '{').replace(']', '}') + ';\n'
            'const appVoiceActionTitles = <String, String>{\n' + '\n'.join(titles) + '\n};\n'
            'const appVoiceActionExecutionKinds = <String, String>{\n' + '\n'.join(execution_kinds) + '\n};\n'
            'const appVoiceActionRisks = <String, String>{\n' + '\n'.join(risks) + '\n};\n'
            'const appVoiceActionCancellable = <String, bool>{\n' + '\n'.join(cancellable) + '\n};\n'
            'const appVoiceActionArgumentSchemas = <String, Map<String, dynamic>>{\n' + '\n'.join(argument_schemas) + '\n};\n'
            'const appVoiceActionPermissions = <String, String?>{\n' + '\n'.join(rows) + '\n};\n'
            'const appVoiceTargetKinds = <String, List<String>>{\n' + '\n'.join(kinds) + '\n};\n'
            'const appVoiceActionParameters = <String, List<String>>{\n' + '\n'.join(parameters) + '\n};\n'
            'const appVoiceTargetActionPermissions = <String, List<String>>{\n' + '\n'.join(target_permissions) + '\n};\n'
            'const appVoiceTargetPermissions = <String, String>' + dart(catalog['target_permissions']) + ';\n')


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = generate()
    if args.check:
        if not args.output.exists() or args.output.read_text() != expected:
            raise SystemExit('Voice capability catalog is out of sync; regenerate the Flutter copy.')
    else:
        args.output.write_text(expected)
