"""Generate the independently deployable Flutter copy of the voice catalog.

python -m app_voice_assistant.generate_catalog --check --output ../DatingApp/lib/services/app_voice/app_voice_capabilities.dart
"""
import argparse
import json
from pathlib import Path


def generate():
    catalog = json.loads(Path(__file__).with_name('capabilities.json').read_text())
    def dart(value):
        return json.dumps(value, ensure_ascii=False)
    rows = []
    for name, action in catalog['actions'].items():
        rows.append(f'  {dart(name)}: {dart(action["permission"])},')
    kinds = [f'  {dart(name)}: <String>{dart(action["target_kinds"])},'
             for name, action in catalog['actions'].items() if action['target_kinds']]
    parameters = [f'  {dart(name)}: <String>{dart(action["parameters"])},'
                  for name, action in catalog['actions'].items() if action['parameters']]
    target_permissions = [f'  {dart(name)}: <String>{dart(action["target_permissions"])},'
                          for name, action in catalog['actions'].items() if 'target_permissions' in action]
    return ('// Generated by Server/app_voice_assistant/generate_catalog.py. Do not edit.\n'
            f'const appVoiceCatalogVersion = {catalog["version"]};\n'
            'const appVoiceActionPermissions = <String, String?>{\n' + '\n'.join(rows) + '\n};\n'
            'const appVoiceTargetKinds = <String, List<String>>{\n' + '\n'.join(kinds) + '\n};\n'
            'const appVoiceActionParameters = <String, List<String>>{\n' + '\n'.join(parameters) + '\n};\n'
            'const appVoiceTargetActionPermissions = <String, List<String>>{\n' + '\n'.join(target_permissions) + '\n};\n'
            'const appVoiceTargetPermissions = <String, String>' + dart(catalog['target_permissions']) + ';\n')


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = generate()
    if args.check:
        if not args.output.exists() or args.output.read_text() != expected:
            raise SystemExit('Voice capability catalog is out of sync; regenerate the Flutter copy.')
    else:
        args.output.write_text(expected)
